export const GENRES_DIR: string = '/genres';

export const GENRES: Record<string, string> = {
    'А в попку лучше': '/anal',
    'Бисексуалы': '/bisexuals',
    'Ваши рассказы': '/your-stories',
    'Гетеросексуалы': '/heterosexuals',
    'Гомосексуалы': '/homosexuals',
    'Группа': '/group',
    'Жена-шлюшка': '/wife-slut',
    'Жено-мужчины': '/wife-men',
    'Золотой дождь': '/golden-shower',
    'Зоофилы': '/zoophiles',
    'Измена': '/infidelity',
    'Инцест': '/incest',
    'Классика': '/classic',
    'Клизма': '/enema',
    'Куни': '/cunnilingus',
    'Лесбиянки': '/lesbians',
    'Молодые': '/young',
    'Наблюдатели': '/observers',
    'Остальное': '/other',
    'Перламутровые брызги': '/pearl-sprinkles',
    'По принуждению': '/forced',
    'Потеря девственности': '/loss-of-virginity',
    'Поэзия': '/poetry',
    'Пушистики': '/fuzzies',
    'Романтика': '/romance',
    'Свингеры': '/swingers',
    'Служебный роман': '/office-romance',
    'Случай': '/case',
    'Странности': '/strangeness',
    'Студенты': '/students',
    'Фантазии': '/fantasies',
    'Фетиш': '/fetish',
    'Фрагменты из запредельного': '/fragments-from-beyond',
    'Экзекуция': '/execution',
    'Эксклюзив': '/exclusive',
    'Эротика': '/erotica',
    'Эротическая сказка': '/erotic-tale',
    'Это славное слово - миньет': '/fellatio',
    'Юмористические': '/humorous',
    'Я хочу пи-пи': '/i-want-to-pee'
};
